services:
    alfredoramos.markdown.listener:
        class: alfredoramos\markdown\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@user'
            - '@request'
            - '@template'
            - '@routing.helper'
            - '@language'
            - '@alfredoramos.markdown.helper'
        tags:
            - { name: event.listener }

    alfredoramos.markdown.controller.markdown:
        class: alfredoramos\markdown\controller\markdown

    alfredoramos.markdown.helper:
        class: alfredoramos\markdown\includes\helper
