name: GitHub Actions CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Prepare RubyGems cache
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle lock --update
    - name: Setup RubyGems cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Install gems
      run: |
        bundle update --jobs 4 --retry 3
        gem cleanup
    - name: Test Ruby
      run: bundle exec rake rubocop
    - name: Test SCSS
      run: bundle exec rake scss_lint
